### ISSUE TITLE
Default branch main instead of master

### ISSUE THREAD

**Issue by olanod** [pksunkara/cargo-workspaces#32]
On a freshly created project from github I ran the version command and got `error: not allowed to run on branch main because it doesn't match pattern master`. Since it will be the default from now on could `main` be the default instead of `master` or have both as allowed branches?

**Comment by pksunkara** [comment]
There are quite a few legacy projects which use `master` and also sometimes new projects that are used with legacy tools. I think #14 once implemented will solve this issue.

**Comment by XAMPPRocky** [comment]
Hey, I think cargo-workspaces should allow both `main` and `master` by default, so that it can work with both new projects and legacy projects, and very rarely would a project ever have both at the same time. I don't consider #14 to be a solution, as I don't want to have to create a config file for this tool in every project I maintain, just to use the new default naming.

**Comment by pksunkara** [comment]
I use https://docs.rs/glob/0.3.0/glob/struct.Pattern.html to match the branch name with a pattern. Unfortunately it doesn't seem like it's possible to do `master|main`. Any idea on how to proceed?

https://github.com/pksunkara/cargo-workspaces/blob/master/cargo-workspaces/src/utils/git.rs#L96

**Comment by XAMPPRocky** [comment]
I think the simplest solution would be to change `allow_branch` to be `Option<String>` so that you can detect its presence by a user, and if not given a value, just try both patterns (one after the other) and error if it matches neither.

**Comment by pksunkara** [comment]
https://github.com/pksunkara/cargo-workspaces/commit/5fa9ae585102f92c094282a80b4863ff3bcf7440 should work if anyone wants to test.
